image: eclipse-temurin:17-jdk

variables:
  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "11076708"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - export ANDROID_HOME="${PWD}/android-sdk-root"
  - mkdir -p "${ANDROID_HOME}/cmdline-tools"
  - wget --quiet --output-document="${ANDROID_HOME}/cmdline-tools.zip" https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -q -d "${ANDROID_HOME}/cmdline-tools" "${ANDROID_HOME}/cmdline-tools.zip"
  - mv "${ANDROID_HOME}/cmdline-tools/cmdline-tools" "${ANDROID_HOME}/cmdline-tools/latest"
  - export PATH="${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools"
  - yes | sdkmanager --licenses > /dev/null || true
  - sdkmanager --install "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  - chmod +x ./gradlew

stages:
  - build

build_apk:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "web"'
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "Pencil2D-Android-APK-$CI_COMMIT_SHORT_SHA"
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 14 days
